# Generated by Django 5.2.17 on 2026-09-14 08:29
from datetime import datetime, timezone
from django.db import migrations

def seed_portfolio_data(apps, schema_editor):
    Experience = apps.get_model("main", "Experience")
    Education = apps.get_model("main", "Education")

    Experience.objects.update_or_create(
        title="AKAR SMADA 2023",
        defaults={
            "role": "Secretary in the Logistics Division",
            "description": (
                "Coordinated logistics and fulfilled various needs for guest "
                "artists while ensuring equipment and supplies were ready."
            ),
            "category": "volunteer",
            "ended_at": datetime(2023, 9, 30, tzinfo=timezone.utc),
        },
    )

    Experience.objects.update_or_create(
        title="APSI 2024",
        defaults={
            "role": "Secretary in the Logistics Division",
            "description": (
                "Managed logistical preparations by documenting essential "
                "materials, organizing item placement, and collaborating "
                "with the decoration team."
            ),
            "category": "volunteer",
            "ended_at": datetime(2024, 8, 31, tzinfo=timezone.utc),
        },
    )

    Experience.objects.update_or_create(
        title="Open House Fasilkom UI 2025",
        defaults={
            "role": "Staff in the Operational Division",
            "description": (
                "Coordinated operational needs, including room reservations, "
                "venue setup, security checks, and participant transportation."
            ),
            "category": "volunteer",
            "ended_at": datetime(2025, 11, 22, tzinfo=timezone.utc),
        },
    )

    Education.objects.update_or_create(
        institution="Universitas Indonesia",
        defaults={
            "program": "Information System",
            "start_year": 2025,
            "end_year": None,
            "activities": "Pekan Ristek Open Class DSAI 2025",
        },
    )

    Education.objects.update_or_create(
        institution="SMAN 2 Depok",
        defaults={
            "program": "High School Diploma, Science",
            "start_year": 2022,
            "end_year": 2025,
            "activities": (
                "APSI, AKAR SMADA, and 2023 National Science Olympiad "
                "at the City Level in Mathematics"
            ),
        },
    )

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.RunPython(seed_portfolio_data),
    ]
