# Generated by Django 5.2.17 on 2026-09-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='message',
            name='relationship',
            field=models.CharField(default='Friend', max_length=100),
            preserve_default=False,
        ),
    ]
