# Generated by Django 5.2.17 on 2026-09-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message_rating_message_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='rating',
        ),
        migrations.AddField(
            model_name='message',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
